name: Lesson 01 Tests

on:
  push:
    paths:
      - 'src/main/kotlin/com/motycka/edu/lesson01/**'
      - 'src/test/kotlin/com/motycka/edu/lesson01/**'
  pull_request:
    paths:
      - 'src/main/kotlin/com/motycka/edu/lesson01/**'
      - 'src/test/kotlin/com/motycka/edu/lesson01/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: true

    - name: Run Lesson 01 Tests
      run: ./gradlew testLesson01
